//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityCare.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommunityCare.Resx.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement.
        /// </summary>
        public static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aleady Added.
        /// </summary>
        public static string Aleady_Added {
            get {
                return ResourceManager.GetString("Aleady_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to cancel the Lab Test?.
        /// </summary>
        public static string Are_you_sure_to_cancel_the_Lab_Test {
            get {
                return ResourceManager.GetString("Are_you_sure_to_cancel_the_Lab_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommCare.
        /// </summary>
        public static string CommCare {
            get {
                return ResourceManager.GetString("CommCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Health Care.
        /// </summary>
        public static string Community_Health_Care {
            get {
                return ResourceManager.GetString("Community_Health_Care", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm and Schedual Pickup.
        /// </summary>
        public static string Confirm_and_Schedual_Pickup {
            get {
                return ResourceManager.GetString("Confirm_and_Schedual_Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Order.
        /// </summary>
        public static string Create_an_Order {
            get {
                return ResourceManager.GetString("Create_an_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time:.
        /// </summary>
        public static string Date_Time {
            get {
                return ResourceManager.GetString("Date_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Lab Test Time and Location.
        /// </summary>
        public static string Edit_Lab_Test_Time_and_Location {
            get {
                return ResourceManager.GetString("Edit_Lab_Test_Time_and_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email_Address {
            get {
                return ResourceManager.GetString("Email_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter correctly..
        /// </summary>
        public static string Enter_correctly {
            get {
                return ResourceManager.GetString("Enter_correctly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email address.
        /// </summary>
        public static string Enter_email_address {
            get {
                return ResourceManager.GetString("Enter_email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting info....
        /// </summary>
        public static string Getting_info {
            get {
                return ResourceManager.GetString("Getting_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Surveies.
        /// </summary>
        public static string Getting_Surveies {
            get {
                return ResourceManager.GetString("Getting_Surveies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting tests.
        /// </summary>
        public static string Getting_tests {
            get {
                return ResourceManager.GetString("Getting_tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of your Lab Tests.
        /// </summary>
        public static string History_of_Your_Lab_Tests {
            get {
                return ResourceManager.GetString("History_of_Your_Lab_Tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of Your Orders.
        /// </summary>
        public static string History_of_Your_Orders {
            get {
                return ResourceManager.GetString("History_of_Your_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of your Surveys.
        /// </summary>
        public static string History_of_Your_Surveys {
            get {
                return ResourceManager.GetString("History_of_Your_Surveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Survey.
        /// </summary>
        public static string Main_Survey {
            get {
                return ResourceManager.GetString("Main_Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Lab Test.
        /// </summary>
        public static string New_Lab_Test {
            get {
                return ResourceManager.GetString("New_Lab_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User Sign up.
        /// </summary>
        public static string New_User_Sign_up {
            get {
                return ResourceManager.GetString("New_User_Sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Detail.
        /// </summary>
        public static string Order_Detail {
            get {
                return ResourceManager.GetString("Order_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string Payment_Method {
            get {
                return ResourceManager.GetString("Payment_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type:.
        /// </summary>
        public static string Payment_Type {
            get {
                return ResourceManager.GetString("Payment_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paypal.
        /// </summary>
        public static string Paypal {
            get {
                return ResourceManager.GetString("Paypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Number.
        /// </summary>
        public static string Pin_Number {
            get {
                return ResourceManager.GetString("Pin_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a lab test.
        /// </summary>
        public static string Please_add_a_lab_test {
            get {
                return ResourceManager.GetString("Please_add_a_lab_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a payment type.
        /// </summary>
        public static string Please_select_a_payment_type {
            get {
                return ResourceManager.GetString("Please_select_a_payment_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Survey.
        /// </summary>
        public static string Quick_Survey {
            get {
                return ResourceManager.GetString("Quick_Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseted password successfully..
        /// </summary>
        public static string Reseted_password_successfully {
            get {
                return ResourceManager.GetString("Reseted_password_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve Password.
        /// </summary>
        public static string Retrieve_Password {
            get {
                return ResourceManager.GetString("Retrieve_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Community Care.
        /// </summary>
        public static string Saudi_Community_Care {
            get {
                return ResourceManager.GetString("Saudi_Community_Care", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Lab Test.
        /// </summary>
        public static string Select_a_Lab_Test {
            get {
                return ResourceManager.GetString("Select_a_Lab_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Payment Type.
        /// </summary>
        public static string Select_a_Payment_Type {
            get {
                return ResourceManager.GetString("Select_a_Payment_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Payment Method.
        /// </summary>
        public static string Select_Payment_Method {
            get {
                return ResourceManager.GetString("Select_Payment_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Location.
        /// </summary>
        public static string Selected_Location {
            get {
                return ResourceManager.GetString("Selected_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Sign_in {
            get {
                return ResourceManager.GetString("Sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up successfully..
        /// </summary>
        public static string Sign_up_successfully {
            get {
                return ResourceManager.GetString("Sign_up_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in.
        /// </summary>
        public static string Signing_in {
            get {
                return ResourceManager.GetString("Signing_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Survey.
        /// </summary>
        public static string Skip_Survey {
            get {
                return ResourceManager.GetString("Skip_Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully send results.\nRecommend Test:.
        /// </summary>
        public static string Successfully_send_results_Recommend_Test {
            get {
                return ResourceManager.GetString("Successfully_send_results_Recommend_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time and Location.
        /// </summary>
        public static string Time_and_Location {
            get {
                return ResourceManager.GetString("Time_and_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We just sent an email with Pin code.
        /// </summary>
        public static string We_just_sent_an_email_with_Pin_code {
            get {
                return ResourceManager.GetString("We_just_sent_an_email_with_Pin_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Saudi Community Care.
        /// </summary>
        public static string Welcome_to_Saudi_CommunityCare {
            get {
                return ResourceManager.GetString("Welcome_to_Saudi_CommunityCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for select Community Health Care.\nYou will recieve the order confirmation on your email..
        /// </summary>
        public static string You_will_recieve_the_order_confirmation_on_your_email {
            get {
                return ResourceManager.GetString("You_will_recieve_the_order_confirmation_on_your_email", resourceCulture);
            }
        }
    }
}
